version: '3'
secrets:
  app:
    build:
      context: .
      dockerfile: dockerfile
      args:
        - PORT=${PORT}
    restart: always
    container_name: cpen321_app
    environment:
      - PORT=${PORT}
    ports:
      - "${PORT}:${PORT}"
    command: npm start